# Testing everytime pushed to develop
name: testing-ci
on:
  push:
    branches:
      - master
jobs:
  fetch_and_check_out:
    name: Fetch & checkout
    runs-on: macos-latest
    steps:
      - name: Echo
        env:
          AUTHOR_NAME: Minh Nguyen
        run: |
          echo Hi $AUTHOR_NAME
  test:
    name: Testing
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: actions/setup-node@master
      - name: Install dependencies && node_modules
        run: |
          yarn install -g && ls -l

      - name: Testing ci
        run: |
          yarn test
